Fix: use psr/container (is used from Symfony container) instead depre…
leroy0211/Slim-Symfony-Dependency-Injection-Bridge pull request #9
Opened 2019-12-10 09:21 UTC by ondraondra81

…cated container-interop/container-interop

2019-12-17 11:42 UTC, ondraondra81 commented
@leroy0211 can you check this please. Thank you

2019-12-20 17:12 UTC, leroy0211 commented
> @leroy0211 can you check this please. Thank you

Looks ok, only 1 minor question about your change. You'll see.

2020-01-20 08:32 UTC, leroy0211 requested changes

2020-01-20 08:32 UTC, leroy0211 commented on composer.json
> +        "phpunit/phpunit": "~7.0"
Could you explain why you changed the caret to a tilde? I don't see why phpunit should only be limited to 7.0.x

2020-01-26 17:33 UTC, ondraondra81 commented on composer.json
> +        "phpunit/phpunit": "~7.0"
I had a problem with version 8.x. I guess I forgot it.

2020-01-27 08:07 UTC, leroy0211 approved these changes

2020-01-27 08:08 UTC, merged